build: 
	west build --build-dir /workspace/01.Emotiv/nrf7002/nrf7002_edge_impulse_test/untitled/build /workspace/01.Emotiv/nrf7002/nrf7002_edge_impulse_test/untitled/ --board nrf7002dk_nrf7001_nrf5340_cpuapp_ns	-- -DNCS_TOOLCHAIN_VERSION=NONE -DCONF_FILE=prj.conf  -DEXTRA_CONF_FILE=nrf7002dk_nrf5340_cpuapp_ns.conf -DDTC_OVERLAY_FILE=nrf7002dk_nrf5340_cpuapp_ns.overlay

clean:
	rm -rf ./build

.PHONY: build
